ALTER TABLE route
  ADD expiry TIMESTAMP;

CREATE TABLE auth (
  ext TEXT NOT NULL,
  pwd TEXT NOT NULL,

  PRIMARY KEY(ext),
  FOREIGN KEY(ext)
    REFERENCES route(ext)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
